import React from 'react';
import {AbsoluteFill, interpolate, useCurrentFrame} from 'remotion';
const BG='#F2F2F2',INK='#222222',SOFT='#8B8B8B',ORANGE='#E07A5F',BLUE='#6D8FB8',WHITE='#FAFAF8';
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const rise=(f:number,at:number,d=18)=>interpolate(f,[at,at+d],[30,0],clamp);
const fade=(f:number,at:number,d=18)=>interpolate(f,[at,at+d],[0,1],clamp);
const Text=({children,size=74,color=INK,weight=700,style={}}:any)=><div style={{fontFamily:'Inter,Arial,sans-serif',fontSize:size,lineHeight:.96,fontWeight:weight,letterSpacing:-2.4,color,...style}}>{children}</div>;
const Small=({children,style={}}:any)=><div style={{fontFamily:'Inter,Arial,sans-serif',fontSize:20,fontWeight:600,letterSpacing:2.2,textTransform:'uppercase',color:SOFT,...style}}>{children}</div>;
const Node=({x,y,accent=false,size=34}:any)=><div style={{position:'absolute',left:x,top:y,width:size,height:size,borderRadius:'50%',background:accent?ORANGE:WHITE,border:`2px solid ${accent?ORANGE:'#555'}`,boxShadow:'0 8px 14px rgba(0,0,0,.12)'}}/>;
const Line=({x,y,w,rotate=0}:any)=><div style={{position:'absolute',left:x,top:y,width:w,height:2,background:'#777',opacity:.38,transform:`rotate(${rotate}deg)`,transformOrigin:'left center'}}/>;
const Network=({compact=false}:any)=>{const s=compact?.78:1;const p=[[0,90],[145,20],[290,80],[70,220],[220,245],[355,175],[175,135]];const e=[[0,1],[1,2],[0,3],[3,4],[4,2],[2,5],[4,5],[1,6],[6,4],[0,6]];return <div style={{position:'absolute',left:520,top:520,transform:`scale(${s})`}}>{e.map(([a,b],i)=><Line key={i} x={p[a][0]+16} y={p[a][1]+16} w={Math.hypot(p[b][0]-p[a][0],p[b][1]-p[a][1])} rotate={Math.atan2(p[b][1]-p[a][1],p[b][0]-p[a][0])*180/Math.PI}/>)}{p.map((v,i)=><Node key={i} x={v[0]} y={v[1]} accent={i===6||i===2} size={i===6?48:34}/>)}</div>};
const Slab=({x,y,w,h,label,accent=ORANGE,rotate=0}:any)=><div style={{position:'absolute',left:x,top:y,width:w,height:h,borderRadius:28,background:WHITE,border:'1px solid rgba(0,0,0,.05)',boxShadow:'0 18px 28px rgba(34,34,34,.16)',transform:`rotate(${rotate}deg)`}}><div style={{position:'absolute',left:24,top:22,width:12,height:12,borderRadius:3,background:accent}}/><div style={{position:'absolute',left:24,bottom:24,fontFamily:'Inter,Arial,sans-serif',fontSize:24,fontWeight:750,color:INK,letterSpacing:-.7}}>{label}</div></div>;
const Beat=({from,to,children}:any)=>{const f=useCurrentFrame();if(f<from-20||f>to+20)return null;const op=interpolate(f,[from,from+16,to-16,to],[0,1,1,0],clamp);const sc=interpolate(f,[from,from+20,to-18,to],[1.02,1,1,.985],clamp);return <AbsoluteFill style={{opacity:op,transform:`scale(${sc})`}}>{children}</AbsoluteFill>};
export const CreatorAudienceStyleDNA:React.FC=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:BG,overflow:'hidden'}}><div style={{position:'absolute',inset:0,background:'radial-gradient(circle at 50% 42%,rgba(255,255,255,.65),transparent 58%)'}}/>
<Beat from={0} to={75}><Small style={{position:'absolute',left:72,top:170,opacity:fade(f,4)}}>CREATOR → AUDIENCE</Small><Text size={104} style={{position:'absolute',left:72,top:245,transform:`translateY(${rise(f,8)}px)`}}>Attention</Text><Text size={104} color={ORANGE} style={{position:'absolute',left:72,top:350,transform:`translateY(${rise(f,18)}px)`}}>+</Text><Text size={104} style={{position:'absolute',left:72,top:435,transform:`translateY(${rise(f,28)}px)`}}>Trust.</Text><Network/><Slab x={690} y={1030} w={290} h={155} label="AUDIENCE"/></Beat>
<Beat from={60} to={150}><Small style={{position:'absolute',left:72,top:150}}>WHY IT MATTERS</Small><Text size={88} style={{position:'absolute',left:72,top:225}}>Years to build.</Text><Text size={58} color={SOFT} style={{position:'absolute',left:74,top:330}}>A new company starts</Text><Text size={58} color={SOFT} style={{position:'absolute',left:74,top:400}}>from almost zero.</Text><div style={{position:'absolute',left:80,top:550,width:800,height:7,background:'#D1D1CE',borderRadius:8}}><div style={{width:`${interpolate(f,[70,140],[5,100],clamp)}%`,height:'100%',background:INK,borderRadius:8}}/></div><Small style={{position:'absolute',left:78,top:590}}>AWARENESS → AUDIENCE → TRUST</Small><Slab x={610} y={800} w={320} h={210} label="BUILD FROM ZERO" accent={BLUE} rotate={-4}/></Beat>
<Beat from={135} to={225}><Small style={{position:'absolute',left:72,top:150}}>THE CREATOR ADVANTAGE</Small><Text size={96} style={{position:'absolute',left:72,top:230}}>Already</Text><Text size={110} color={ORANGE} style={{position:'absolute',left:72,top:335}}>has it.</Text><Network compact/><div style={{position:'absolute',left:75,top:710,width:820,height:2,background:'#777',opacity:.3}}/><Small style={{position:'absolute',left:75,top:735}}>ESTABLISHED AUDIENCE</Small></Beat>
<Beat from={210} to={300}><Small style={{position:'absolute',left:72,top:145}}>TURN ATTENTION INTO VALUE</Small><Text size={76} style={{position:'absolute',left:72,top:220}}>Product</Text><Text size={76} color={ORANGE} style={{position:'absolute',left:72,top:305}}>Service</Text><Text size={76} style={{position:'absolute',left:72,top:390}}>Brand</Text><Slab x={585} y={210} w={330} h={170} label="PRODUCT"/><Slab x={640} y={460} w={330} h={170} label="SERVICE" accent={BLUE} rotate={-3}/><Slab x={540} y={710} w={330} h={170} label="BRAND" accent={INK} rotate={4}/></Beat>
<Beat from={285} to={390}><Small style={{position:'absolute',left:72,top:145}}>THE BUSINESS ASSET</Small><Text size={76} style={{position:'absolute',left:72,top:220}}>Not just</Text><Text size={92} color={ORANGE} style={{position:'absolute',left:72,top:315}}>followers.</Text><Text size={68} style={{position:'absolute',left:72,top:445}}>It is an asset</Text><Text size={68} style={{position:'absolute',left:72,top:515}}>when used right.</Text><Network compact/><Slab x={635} y={910} w={340} h={175} label="BUSINESS ASSET" accent={ORANGE}/></Beat>
<Beat from={375} to={450}><div style={{position:'absolute',inset:0,background:'#EAEAE7'}}/><Text size={98} style={{position:'absolute',left:70,top:510}}>USE IT RIGHT</Text><Small style={{position:'absolute',left:74,top:640}}>AUDIENCE → VALUE</Small></Beat></AbsoluteFill>};
